<?= $this->extend('layouts/main') ?><?= $this->section('content') ?>
<?php $editing=$user!==null; $errors=session()->getFlashdata('errors') ?? []; ?>
<header class="page-head"><p class="kicker">Staff register</p><h1><?= $editing?'Edit staff account':'New staff account' ?></h1><p><?= $editing?'Update identity, access, or profile image.':'Create protected access for a team member.' ?></p></header>
<?php if($avatarNotice): ?><div class="flash flash-info" role="status"><strong>Avatar storage:</strong> <?= esc($avatarNotice) ?></div><?php endif ?>
<form class="form-panel form-wide" action="<?= $editing?'/users/'.(int)$user['id']:'/users' ?>" method="post" enctype="multipart/form-data"><?= csrf_field() ?>
<div class="form-grid"><div class="field"><label for="username">Username</label><input id="username" name="username" autocomplete="username" maxlength="50" required value="<?= esc(old('username',$user['username']??'')) ?>" <?= isset($errors['username'])?'aria-invalid="true" aria-describedby="username-error"':'' ?>><p class="hint">Letters, numbers, dots, hyphens, and underscores.</p><?php if(isset($errors['username'])):?><p class="field-error" id="username-error"><?= esc($errors['username']) ?></p><?php endif ?></div>
<div class="field"><label for="full_name">Full name</label><input id="full_name" name="full_name" autocomplete="name" maxlength="100" required value="<?= esc(old('full_name',$user['full_name']??'')) ?>" <?= isset($errors['full_name'])?'aria-invalid="true" aria-describedby="full_name-error"':'' ?>><?php if(isset($errors['full_name'])):?><p class="field-error" id="full_name-error"><?= esc($errors['full_name']) ?></p><?php endif ?></div></div>
<div class="field"><label for="role">Role</label><select id="role" name="role" required><?php $selected=old('role',$user['role']??''); ?><option value="">Select a role</option><?php foreach($roles as $role): ?><option value="<?= esc($role,'attr') ?>" <?= $selected===$role?'selected':'' ?>><?= esc($role) ?></option><?php endforeach ?></select><?php if(isset($errors['role'])):?><p class="field-error" id="role-error"><?= esc($errors['role']) ?></p><?php endif ?></div>
<fieldset><legend><?= $editing?'Replace password':'Set password' ?></legend><?php if($editing): ?><p class="hint">Leave both fields blank to keep the existing password.</p><?php endif ?><div class="form-grid"><div class="field"><label for="password">Password</label><input id="password" type="password" name="password" autocomplete="new-password" <?= $editing?'':'required' ?> minlength="10" maxlength="128"><?php if(isset($errors['password'])):?><p class="field-error" id="password-error"><?= esc($errors['password']) ?></p><?php endif ?></div><div class="field"><label for="password_confirm">Confirm password</label><input id="password_confirm" type="password" name="password_confirm" autocomplete="new-password" <?= $editing?'':'required' ?>><?php if(isset($errors['password_confirm'])):?><p class="field-error" id="password_confirm-error"><?= esc($errors['password_confirm']) ?></p><?php endif ?></div></div></fieldset>
<div class="avatar-field"><img src="<?= esc($avatarUrl,'attr') ?>" width="96" height="96" alt="Current avatar preview"><div class="field"><label for="avatar">Profile image <span class="optional">Optional</span></label><input id="avatar" type="file" name="avatar" accept="image/jpeg,image/png" <?= $avatarNotice?'disabled':'' ?>><p class="hint">JPEG or PNG, up to 2 MB. The image is cropped to a 256px square.</p><?php if(isset($errors['avatar'])):?><p class="field-error" id="avatar-error"><?= esc($errors['avatar']) ?></p><?php endif ?></div></div>
<div class="form-actions"><button class="button" type="submit"><?= $editing?'Save account':'Create account' ?></button><a class="button-secondary" href="/users">Cancel</a></div></form>
<?= $this->endSection() ?>
